Repository WeAreSide/DNFCal, pull requests merged in 2024-01, with the labels that each got.

#2 [Setting/#1] Issue, PR 템플릿 추가, README 추가, gitignore 추가
  .DS_Store
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
Labels: Setting

#8 [Assets/#7] 에셋추가, 폴더링(더미 파일 추가 예정), 폰트 추가
  dnf_cal/assets/fonts/DNFForgedBlade-Bold.otf
  dnf_cal/assets/fonts/DNFForgedBlade-Light.otf
  dnf_cal/assets/fonts/DNFForgedBlade-Medium.otf
  dnf_cal/assets/images/character_background.png
  dnf_cal/assets/images/default_background.png
  dnf_cal/lib/main.dart
  dnf_cal/lib/models/model_explain.txt
  dnf_cal/lib/screens/screen_explain.txt
  dnf_cal/lib/service/service_explain.txt
  dnf_cal/lib/utils/util_explain.txt
  dnf_cal/lib/widgets/widget_explain.txt
  dnf_cal/pubspec.yaml
Labels: Asset, Setting

#10 [Feat/#9] BottomNavigationBar 기본 구현, 이미지 2배율 3배율 추가
  .DS_Store
  dnf_cal/assets/images/2.0x/character_background.png
  dnf_cal/assets/images/2.0x/default_background.png
  dnf_cal/assets/images/3.0x/character_background.png
  dnf_cal/assets/images/3.0x/default_background.png
  dnf_cal/assets/images/character_background.png
  dnf_cal/assets/images/default_background.png
  dnf_cal/lib/main.dart
  dnf_cal/lib/screens/CharacterSearchPage.dart
  dnf_cal/lib/screens/SettingPage.dart
  dnf_cal/pubspec.yaml
Labels: Feat, Asset

#12 [Feat/#11] 1, 2번째 탭 더미 추가
  dnf_cal/lib/main.dart
  dnf_cal/lib/screens/MainPage.dart
  dnf_cal/lib/screens/RegisterCharacterPage.dart
Labels: Feat

#14 [Setting/#13] Color set 추가
  dnf_cal/lib/models/CustomColor.dart
  dnf_cal/lib/screens/CharacterSearchPage.dart
Labels: Setting

#17 [Feat/#16] 등록된 캐릭터 편집버튼 구현 추가 캐릭터 등록 해제 토글 및 버튼, 해제 알림창
  dnf_cal/lib/screens/RegisterCharacterPage.dart
Labels: Feat

#19 [Feat/#18] 추가 임시달력
  dnf_cal/lib/screens/MainPage.dart
  dnf_cal/pubspec.yaml
Labels: Feat

#20 [Feat/#15] 캐릭터 검색 화면 레이아웃 구현
  .DS_Store
  dnf_cal/ios/Runner.xcodeproj/project.pbxproj
  dnf_cal/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  dnf_cal/lib/main.dart
  dnf_cal/lib/models/CustomColor.dart
  dnf_cal/lib/models/SearchModel.dart
  dnf_cal/lib/screens/CharacterSearchPage.dart
  dnf_cal/lib/screens/SettingPage.dart
  dnf_cal/lib/widgets/CharacterSearch/CharacterSearchBar.dart
  dnf_cal/lib/widgets/CharacterSearch/CharacterSearchTopWidget.dart
  dnf_cal/lib/widgets/CharacterSearch/SearchResultTitleWidget.dart
  dnf_cal/lib/widgets/CharacterSearch/ServerSelectionWidget.dart
  dnf_cal/lib/widgets/global/BottomNavigationWidget.dart
  dnf_cal/lib/widgets/global/DefaultBackgroundWidget.dart
  dnf_cal/pubspec.lock
  dnf_cal/pubspec.yaml
Labels: Feat

#23 [Setting/#22] iOS 빌드 버그 수정
  dnf_cal/ios/Runner.xcodeproj/project.pbxproj
Labels: Bug, Setting

#26 [Fix/#21] 1, 2번째 페이지 디자인 수정 및 상세화
  dnf_cal/lib/screens/MainPage.dart
  dnf_cal/lib/screens/RegisterCharacterPage.dart
Labels: Fix

#27 [Feat/#25] 검색 캐릭터 정보 셀 UI 구현
  .DS_Store
  dnf_cal/assets/images/2.0x/character_background.png
  dnf_cal/assets/images/2.0x/dummy_character.png
  dnf_cal/assets/images/3.0x/character_background.png
  dnf_cal/assets/images/3.0x/dummy_character.png
  dnf_cal/assets/images/character_background.png
  dnf_cal/assets/images/dummy_character.png
  dnf_cal/lib/main.dart
  dnf_cal/lib/screens/CharacterSearchPage.dart
  dnf_cal/lib/widgets/CharacterSearch/SearchCharacterCellScroll.dart
  dnf_cal/lib/widgets/SearchCharacterCell.dart
  dnf_cal/pubspec.lock
  dnf_cal/pubspec.yaml
Labels: Feat

#30 [Fix/#28] 달력 페이지, 등록된 캐릭터 페이지 디자인 수정
  dnf_cal/lib/screens/MainPage.dart
  dnf_cal/lib/screens/RegisterCharacterPage.dart
Labels: Fix

#32 [Feat/#29] 설정 페이지 구현
  dnf_cal/lib/screens/OpenSourcePage.dart
  dnf_cal/lib/screens/PrivacyPolicyPage.dart
  dnf_cal/lib/screens/SettingPage.dart
  dnf_cal/lib/widgets/CharacterSearch/CharacterSearchTopWidget.dart
  dnf_cal/lib/widgets/CharacterSearch/SearchResultTitleWidget.dart
  dnf_cal/lib/widgets/Setting/OpenSourceNavigationBar.dart
  dnf_cal/lib/widgets/Setting/PrivacyPolicyNavigationBar.dart
  dnf_cal/lib/widgets/Setting/SettingTopWidget.dart
  dnf_cal/lib/widgets/global/BottomNavigationWidget.dart
Labels: Feat

#33 [Refactor/#31] 달력 페이지, 등록된 캐릭터 페이지 Refactoring
  .DS_Store
  .idea/.gitignore
  .idea/DNFCal.iml
  .idea/modules.xml
  .idea/vcs.xml
  dnf_cal/lib/models/CustomColor.dart
  dnf_cal/lib/screens/MainPage.dart
  dnf_cal/lib/screens/RegisterCharacterPage.dart
  dnf_cal/lib/screens/SettingPage.dart
  dnf_cal/lib/widgets/CharacterSearch/CharacterSearchTopWidget.dart
  dnf_cal/lib/widgets/CharacterSearch/SearchResultTitleWidget.dart
  dnf_cal/lib/widgets/CharacterSearch/ServerSelectionWidget.dart
  dnf_cal/lib/widgets/MainPage/AdventureInfo.dart
  dnf_cal/lib/widgets/MainPage/CalendarBuilder/BuildCalendarBuilders.dart
  dnf_cal/lib/widgets/MainPage/CalendarSpace.dart
  dnf_cal/lib/widgets/MainPage/CalendarStyle.dart/BuildCalendarStyle.dart
  dnf_cal/lib/widgets/MainPage/CalendarStyle.dart/BuildDaysOfWeekStyle.dart
  dnf_cal/lib/widgets/MainPage/CalendarStyle.dart/BuildHeaderStyle.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/CharacterProfile.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/DeleteRegisterCharacterButton.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/RegisterChracterEditBar.dart
  dnf_cal/lib/widgets/SearchCharacterCell.dart
  dnf_cal/lib/widgets/Setting/OpenSourceNavigationBar.dart
  dnf_cal/lib/widgets/Setting/PrivacyPolicyNavigationBar.dart
  dnf_cal/lib/widgets/Setting/SettingTopWidget.dart
  dnf_cal/lib/widgets/global/DnfText.dart
Labels: Fix, Refactor

#35 [Fix/#34] 설정탭 Expanded 관련 디버그 에러 수정
  dnf_cal/lib/widgets/Setting/SettingTopWidget.dart
Labels: Fix

#37 [Refactor/#36] 등록된 캐릭터 페이지에 provider 적용
  dnf_cal/lib/models/RegisterCharacterModel.dart
  dnf_cal/lib/screens/RegisterCharacterPage.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/CharacterProfile.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/DeleteRegisterCharacterButton.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/RegisterChracterEditBar.dart
Labels: Refactor

#39 [Feat/#38] 캐릭터 검색 API 구현
  .gitignore
  dnf_cal/lib/main.dart
  dnf_cal/lib/models/SearchCharacterModel.dart
  dnf_cal/lib/models/SearchCharacterModel.g.dart
  dnf_cal/lib/models/SearchModel.dart
  dnf_cal/lib/screens/CharacterSearchPage.dart
  dnf_cal/lib/utils/APIModel.dart
  dnf_cal/lib/widgets/CharacterSearch/CharacterSearchBar.dart
  dnf_cal/lib/widgets/CharacterSearch/SearchAndFilterWidget.dart
  dnf_cal/lib/widgets/CharacterSearch/SearchCharacterCellScroll.dart
  dnf_cal/lib/widgets/CharacterSearch/SearchResultTitleWidget.dart
  dnf_cal/lib/widgets/CharacterSearch/ServerSelectionWidget.dart
  dnf_cal/lib/widgets/SearchCharacterCell.dart
  dnf_cal/pubspec.lock
  dnf_cal/pubspec.yaml
Labels: Feat

#41 [Fix/#40] 서버 선택 한글로 변경, 검색결과 없을시 텍스트 표시, 네트워크 이미지 공간 잡기
  dnf_cal/lib/models/SearchModel.dart
  dnf_cal/lib/screens/CharacterSearchPage.dart
  dnf_cal/lib/widgets/CharacterSearch/CharacterSearchBar.dart
  dnf_cal/lib/widgets/CharacterSearch/SearchCharacterCellScroll.dart
  dnf_cal/lib/widgets/SearchCharacterCell.dart
Labels: Fix

#43 [Fix/#42] 검색일부 검색 수정, 드롭다운 메뉴 버그수정
  dnf_cal/lib/utils/APIModel.dart
  dnf_cal/lib/widgets/CharacterSearch/SearchResultTitleWidget.dart
Labels: Fix

#45 [fix/#44] 캐릭터 검색량 api url 수정
  dnf_cal/lib/utils/APIModel.dart
Labels: Fix

#47 [Feat/#46] 캐릭터 등록 기능 구현
  dnf_cal/ios/Flutter/Debug.xcconfig
  dnf_cal/ios/Flutter/Release.xcconfig
  dnf_cal/ios/Podfile
  dnf_cal/ios/Podfile.lock
  dnf_cal/ios/Runner.xcodeproj/project.pbxproj
  dnf_cal/ios/Runner.xcworkspace/contents.xcworkspacedata
  dnf_cal/lib/main.dart
  dnf_cal/lib/models/RegisterCharacterModel.dart
  dnf_cal/lib/models/SearchCharacterModel.g.dart
  dnf_cal/lib/realm/Chracter.dart
  dnf_cal/lib/realm/Chracter.g.dart
  dnf_cal/lib/screens/CharacterSearchPage.dart
  dnf_cal/lib/screens/RegisterCharacterPage.dart
  dnf_cal/lib/utils/APIModel.dart
  dnf_cal/lib/widgets/CharacterSearch/CharacterSearchBar.dart
  dnf_cal/lib/widgets/CharacterSearch/SearchCharacterCellScroll.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/CharacterProfile.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/DeleteRegisterCharacterButton.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/RegisterChracterEditBar.dart
  dnf_cal/lib/widgets/SearchCharacterCell.dart
  dnf_cal/linux/flutter/generated_plugin_registrant.cc
  dnf_cal/linux/flutter/generated_plugins.cmake
  dnf_cal/macos/Flutter/Flutter-Debug.xcconfig
  dnf_cal/macos/Flutter/Flutter-Release.xcconfig
  dnf_cal/macos/Flutter/GeneratedPluginRegistrant.swift
  dnf_cal/macos/Podfile
  dnf_cal/pubspec.lock
  dnf_cal/pubspec.yaml
  dnf_cal/windows/flutter/generated_plugin_registrant.cc
  dnf_cal/windows/flutter/generated_plugins.cmake
Labels: Feat

#49 [Fix/#48] 캐릭터 등록 문구 바로 바뀌도록 수정
  dnf_cal/lib/models/RegisterCharacterModel.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/RegisterChracterEditBar.dart
Labels: Fix

#51 [Feat/#50] 달력 페이지 DB 연동
  dnf_cal/lib/main.dart
  dnf_cal/lib/models/RegisterCharacterModel.dart
  dnf_cal/lib/realm/Calendar.dart
  dnf_cal/lib/realm/Calendar.g.dart
  dnf_cal/lib/realm/Character.dart
  dnf_cal/lib/realm/Character.g.dart
  dnf_cal/lib/screens/CharacterSearchPage.dart
  dnf_cal/lib/screens/MainPage.dart
  dnf_cal/lib/screens/RegisterCharacterPage.dart
  dnf_cal/lib/utils/APIModel.dart
  dnf_cal/lib/widgets/MainPage/AdventureInfo.dart
  dnf_cal/lib/widgets/MainPage/CalendarSpace.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/CharacterProfile.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/RegisterChracterEditBar.dart
Labels: Feat

#53 [Asset/#52] 앱 아이콘, 명성 아이콘 추가 및 적용
  dnf_cal/assets/images/2.0x/app_icon.png
  dnf_cal/assets/images/2.0x/fame_icon.png
  dnf_cal/assets/images/3.0x/app_icon.png
  dnf_cal/assets/images/3.0x/fame_icon.png
  dnf_cal/assets/images/app_icon.png
  dnf_cal/assets/images/fame_icon.png
  dnf_cal/lib/widgets/CharacterSearch/CharacterSearchTopWidget.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/CharacterProfile.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/RegisterChracterEditBar.dart
  dnf_cal/lib/widgets/Setting/SettingTopWidget.dart
  dnf_cal/pubspec.yaml
Labels: Feat, Asset, Fix

#55 [Feat/#54] 달력 디자인 수정
  dnf_cal/lib/widgets/MainPage/CalendarBuilder/BuildCalendarBuilders.dart
Labels: Feat

#57 [feat/#56] 이전 날짜의 캐릭터를 확인하는 페이지 추가
  dnf_cal/lib/models/RegisterCharacterModel.dart
  dnf_cal/lib/screens/PastCharacterInfoPage.dart
  dnf_cal/lib/widgets/MainPage/CalendarBuilder/BuildCalendarBuilders.dart
  dnf_cal/lib/widgets/MainPage/PastCharacterInfoNavigationBar.dart
Labels: Feat

#59 [Feat/#58] 개인정보 처리방침 페이지 , 오픈소스 라이브러리 추가
  dnf_cal/android/app/src/main/AndroidManifest.xml
  dnf_cal/ios/Runner/Info.plist
  dnf_cal/lib/screens/SettingPage.dart
  dnf_cal/lib/widgets/Setting/PrivacyPolicyNavigationBar.dart
Labels: Feat

#66 [Fix/#65] 화면 회전 대응관련 수정
  dnf_cal/lib/main.dart
  dnf_cal/lib/widgets/MainPage/CalendarBuilder/BuildCalendarBuilders.dart
  dnf_cal/lib/widgets/RegisterCharacterPage/CharacterProfile.dart
Labels: Fix

#68 [fix/#67] 이전 기록이 갱신되는 현상 수정
  dnf_cal/ios/Podfile.lock
  dnf_cal/lib/models/RegisterCharacterModel.dart
  dnf_cal/lib/realm/Calendar.dart
  dnf_cal/lib/realm/Calendar.g.dart
  dnf_cal/lib/screens/PastCharacterInfoPage.dart
  dnf_cal/lib/widgets/MainPage/CalendarBuilder/BuildCalendarBuilders.dart
Labels: Fix

#70 [fix/#69] 480레벨 색 수정
  dnf_cal/lib/screens/PastCharacterInfoPage.dart
Labels: Fix
